TRAINER:
  debug: false
  device: cuda
  dataset_type: technicolor
  renderer: diff_gaussian_rasterization
  forward_renderer: forward_lite
  model_type: spacetime_360
  model_path: output/spacetime_360
  load_iteration: null
  max_iterations: 30000
  saving_iterations: [200, 1700, 3000, 5000, 8000, 10000, 15000, 20000, 25000, 30000]
  trainer_seed: 0
  lambda_dssim: 0.2
  method_mask_loss: none
  parallel_load: false
  num_workers_load: 16
  model_params:
    lambda_mask: 0.001
    color_transform:
      enable: true
      lambda_loss: 0.01
      model_path_prior: null
      lr:
        init: 0.05
        final: 0.0005
        delay_steps: null
        delay_mult: null
        max_steps: null
    density_control:
      enable: true
      split_num: 2
      split_ratio: 0.5
      th_method: simple
      grad_th_xyz: 0.001
      scale_th_xyz: 0.01
      start: null
      step: null
      end: null
    reset_opacity:
      enable: true
      start: null
      step: null
      end: null
    prune_points:
      enable: true
      start: 2
      step: null
      end: null
      th_opacity: 0.005
      th_radii: 999999
    learning_rate:
      xyz:
        init: 0.00016
        final: 0.0000016
        delay_steps: null
        delay_mult: null
        max_steps: null
      xyz_scales: 0.005
      rotation: 0.001
      opacity: 0.05
      features_dc: 0.0025
    spacetime:
      t_scale_init: -2.0
      motion_degree: 3
      omega_degree: 1
      time_density_control:
        enable: false
        split_ratio: 0.74
        th_grad: 0.00002
        th_scale: 0.0002
      learning_rate:
        t: 0.0001
        t_scale: 0.03
        motion: 3.5
        omega: 0.0001
    static:
      ply_path: /home/wsq/Data/SSD/ours/movingrig/data/v4/dynamic/camera_calibration/input_ply/static.ply
      border_control:
        method: simple
        th_convert: -1
  dataset_params:
    source_path: /home/wsq/Data/SSD/ours/movingrig/data/v4/dynamic/camera_calibration
    relative_mask_path: masks_foreground
    resolution_scale: 2.0
    is_eval: true
    train_test_split_seed: 0
    near: 0.01
    far: 100.0
    lazy_load: true
    ply_path: null
    data_device: cpu
    int8_mode: true
    time_params:
      frame_rate: 60
      start_frame: 3000
      duration: 60